import { writeFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { scanChangedFiles } from './scanner.js';
import { generateDoc, docOutputPath } from './writer.js';

const DRY_RUN = process.env.DRY_RUN === '1';
const REPO_ROOT = process.env.REPO_ROOT
  ?? path.resolve(new URL('.', import.meta.url).pathname, '../../..');

function log(msg) {
  process.stdout.write(JSON.stringify({ ts: new Date().toISOString(), ...msg }) + '\n');
}

async function run() {
  const files = await scanChangedFiles();

  if (files.length === 0) {
    log({ event: 'auto_docs.no_changes' });
    return;
  }

  log({ event: 'auto_docs.start', files: files.length, dry_run: DRY_RUN });

  let generated = 0;
  let errors = 0;

  for (const file of files) {
    try {
      log({ event: 'doc.generating', file: file.rel });

      const markdown = await generateDoc(file);
      const outPath = docOutputPath(file.rel, REPO_ROOT);

      if (!DRY_RUN) {
        await mkdir(path.dirname(outPath), { recursive: true });
        const header = `<!-- auto-generated by auto-docs — do not edit manually -->\n# \`${file.rel}\`\n\n`;
        await writeFile(outPath, header + markdown, 'utf8');
      }

      log({ event: 'doc.written', file: file.rel, out: path.relative(REPO_ROOT, outPath), dry_run: DRY_RUN });
      generated++;
    } catch (err) {
      log({ event: 'doc.error', file: file.rel, error: err.message });
      errors++;
    }
  }

  log({ event: 'auto_docs.complete', generated, errors, dry_run: DRY_RUN });

  if (errors > 0) process.exit(1);
}

run().catch(err => {
  process.stderr.write(JSON.stringify({ level: 'error', event: 'auto_docs.fatal', error: err.message }) + '\n');
  process.exit(1);
});
