# Rewrite Labs – Outreach Templates
# File: docs/outreach-templates.md
# Date: 2026-04-26
# Version: v1.1.0
# Moved from: outreach/outreach-templates.md

---

## Purpose
Templates for outreach communications generated by `pipeline/40-outreach/index.js`.

## Email Template

```
Subject: A modern redesign preview of your website

Hi,

I generated a redesign concept for your website that focuses on clearer layout,
better mobile experience, and stronger calls to action.

Highlights:
- Updated hero section with a clear primary CTA
- Structured sections for services, testimonials, and contact
- Responsive layout designed for phones, tablets, and desktops

If you'd like to see the full preview and implementation notes, I can send them over.

Best,
Chris
```

## SMS Template

```
Hi, I created a modern redesign preview of your website with improved layout
and mobile experience. Want to see it?
```

## Proposal Template

```
Your redesigned website focuses on:
- Clear, modern layout
- Mobile-first responsiveness
- Strong, visible calls to action
- Structured sections for services, proof, and contact

We can turn this concept into a live site with a fast turnaround
and predictable pricing.
```

## Pricing

- $50 one-time redesign
- $10–$25/mo optional hosting + maintenance
- Upsell: full brand refresh

## Follow-up Sequence

- Day 1: Initial outreach (email + SMS)
- Day 3: Follow-up if no reply
- Day 7: Final follow-up with redesign preview link
